@interface NCNotificationOptions : NSObject
@property (nonatomic,readonly) BOOL dismissAutomatically;
@property (nonatomic,readonly) BOOL overridesQuietMode;
@property (nonatomic,readonly) BOOL alertsWhenLocked;
@property (nonatomic,readonly) BOOL addToLockScreenWhenUnlocked;
@property (nonatomic,readonly) NSUInteger lockScreenPersistence;
@property (nonatomic,readonly) NSUInteger lockScreenPriority;
@property (nonatomic,readonly) NSUInteger realertCount;
@property (nonatomic,readonly) BOOL suppressesAlertsWhenAppIsActive;
@property (nonatomic,readonly) BOOL canPlaySound;
@property (nonatomic,readonly) BOOL canTurnOnDisplay;
@property (nonatomic,readonly) BOOL requestsFullScreenPresentation;
@property (nonatomic,readonly) BOOL preemptsPresentedNotification;
@property (nonatomic,readonly) BOOL revealsAdditionalContentOnPresentation;
@property (nonatomic,readonly) BOOL suppressesTitleWhenLocked;
@property (nonatomic,readonly) BOOL suppressesSubtitleWhenLocked;
@property (nonatomic,readonly) BOOL suppressesBodyWhenLocked;
@property (nonatomic,readonly) NSUInteger contentPreviewSetting;
@property (nonatomic,readonly) BOOL silencedByMenuButtonPress;
@property (nonatomic,readonly) BOOL overridesPocketMode;
@property (nonatomic,readonly) BOOL hideClearActionInList;
@property (nonatomic,readonly) NSUInteger messageNumberOfLines;
@property (nonatomic,readonly) BOOL coalescesWhenLocked;
@property (nonatomic,readonly) BOOL preventsAutomaticLock;
@property (nonatomic,readonly) BOOL revealsAdditionalContentIfNoDefaultAction;
@end